### PR TITLE
Mega plus cleanliness

### PR DESCRIPTION
**Pull request by 13r0ck**
Please make sure that this doesn't break https://github.com/pop-os/alsa-ucm-conf/pull/1 or https://github.com/pop-os/alsa-ucm-conf/pull/2 (specifically commit https://github.com/pop-os/alsa-ucm-conf/pull/2/commits/31f976e82fc065f7104b2dd70055b9950592b422)

### CODE REVIEW

**Comment by 13r0ck** [comment]
Converting to a draft, because this 99% works for mega audio, but the C/Sub and Rear jacks are flipped for some reason

**Comment by XV-02** [comment]
This PR is removing detection of the `Rear` and `Centre/Sub` channels on Mira B1.
Specifically, fully updated Pop without this version of alsa-ucm-conf displays a 7.1 style audio test card, and the 5.1 channels (front & rear left & right, subwoofer, and front center) all output when tested. 
With this version of the package, only the 2 channel stereo test card appears, and while front left&right tests correctly, the remaining channels seem not to be recognized.

**Comment by XV-02** [comment]
Audio out now behaves correctly on Mira B1. However, both the Mic In and Line In seem to be mapped to the Line In port. 

Barring S/PDIF, audio behaviour is right and proper on Mega R2.

**Review by XV-02 — APPROVED** [review]
This now resolves the block on the Mira B1, and resolves socket issues on Mega R2

**Review by mmstick — APPROVED** [review]

**Pull request merged**
