### PR TITLE
USB-Audio: ALC4080: Add USB ID 0b05:1a5c (ASUS ROG Strix B650E-I)

### PR DESCRIPTION
**Pull request by leviport**
Attempt to fix line-in and mic-in on thelio-r4 by picking https://github.com/alsa-project/alsa-ucm-conf/commit/309d2afd758accd051b3d1e67b586d2b4d546bda

### CODE REVIEW

**Comment by leviport** [comment]
Yay, it works!

**Review by jackpot51 — APPROVED** [review]

**Comment by leviport** [comment]
@jacobktm caught something in the regex that got removed when copying from upstream: https://github.com/pop-os/alsa-ucm-conf/pull/18/commits/abf69a77963b5ff674ae56556f10eef47e338bdb

The `(b|e)` part is probably needed for major-r5.  Since it went from our `a00(b|e)` to `a0(0e|...)`, I just added an extra `0b` to make it `a0(0b|0e|...)`. Hopefully that still works. I'll test it on major-r5 as well.

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
I looked carefully and verified that the regex only adds IDs (after your latest commit).

**Comment by leviport** [comment]
Alright, I've confirmed that both major-r5 and thelio-r4 have working sound with this update.

**Pull request merged**
