### PR TITLE
Rebase on 1.2.7 & Fix Audio Jacks on Mira B1

### PR DESCRIPTION
**Pull request by 13r0ck**
This PR does the following:

1, Rebases a few upstream changes. This will put us on version 1.2.7, rather than the arbitrary commit version we had released.
2. Fixes the line-in and mic on the mira b1

Requires pop-os/linux/pull/146
Requires pop-os/libasound2/pull/1

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by linuxgnuru** [comment]
Mic and line-in worked as intended.

**Comment by linuxgnuru** [comment]
Could not get line in audio to function

**Comment by XV-02** [comment]
When I check the alsa's version, I keep seeing version `1.2.6.3-1ubuntu2pop1~1654283022~22.04~31f976e`. The appended hash matches one of the commits for the branch associated with this PR (`31f976e`) but I'm not entirely certain that alsa is being upgraded correctly and fully given that this should rebase to `1.2.7`

**Comment by 13r0ck** [comment]
Oh good catch. I need to add a commit like:
https://github.com/pop-os/linux/commit/63e51bd1d6b2e19368234698a9fd67e91955c702

 to modify the changelog file

**Comment by XV-02** [comment]
Near as I can tell, this isn't resolving the Mira-b1 audio conundrum. I'd spin the 1.2.7 rebase off into an isolated PR, and consider closing this in the meantime or continuing the Mira-b1 specific work through this PR.

**Comment by XV-02** [comment]
This is working for Mira-B1. Currently ensuring no regressions elsewhere.

**Review by jackpot51 — APPROVED** [review]

**Review by XV-02 — APPROVED** [review]
In concert with https://github.com/pop-os/libasound2/pull/1 and https://github.com/pop-os/linux/pull/146, this is both working, and not inducing any detectable regressions in other hardware.

**Pull request merged**
